server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## User Service (Authentication Service)
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1
            ## Event Service (Protected by JWT)
            - id: event-service-route
              uri: lb://event-service
              predicates:
                - Path=/api/event/**
              filters:
                - StripPrefix=1
                - JwtValidation
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
