spring.application.name=event-service
server.port=4005
spring.datasource.url=jdbc:postgresql://localhost:5432/event-service
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always


management.endpoints.web.exposure.include=health, metrics, prometheus
management.metrics.tags.application=event-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/